name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  run-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.11"

      - name: Run Claude Code Action
        uses: raichi0618/claude-code-action@main
        with:
          access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
